# Computational skills

The high-performance computer we'll use for our data doesn't have the graphical interface
you usually use (like a PC or Mac).
That means you have to type in your commands - you can't point and click.
This actually has a hidden benefit because it's easy to write down what you did in
a line of text rather than having to try to explain where to click on each step.

Let's start by learning how to access our server and run commands without clicking.

## Log in to the server

For this duration of this workshop you will have access to a server at the University of Rhode Island. Go to `rstudio.uri.edu` and log in with the first part of your email address as both the username and password. Click on the `Terminal` tab to access the command line interface.

## Basic navigation

To see the list of files on this computer in your "home" directory do the following:

```
ls
```

This folder might be empty because you haven't put anything here.
Let's start our project by getting organized.

We will use both R code and bash/shell scripts in this workshop.
Because RStudio provides a mechanism for setting up projects we will use this to stay organized.
In the RStudio File menu select New Project - New Directory - New Project.

* Give the project a name (e.g. evolution_workshop). For this and all future work ensure that names never include spaces.
* Select R 4.1.2
* Create Project

By creating a new project you have created a folder for your work.
When using projects whenever you come back to this project you will return to the same setup.
This allows you to switch projects with different folders and open files.

We will begin our work using the command line or shell.
Select the Terminal tab.
First, make a directory to put your scripts in inside your workshop folder.
We'll write these scripts in a little while, but basically a script is a list of commands that you will give the computer to do all the steps to analyze your data.

Start by checking which folder you are in using the following command.

```
pwd
```

If you are already in your project folder you may skip the next step.
Otherwise you must move into that directory. 
To change directories you need two things - the command to change directory and the argument that specifies which directory to move into.

```
cd evolution_workshop
```

To make a directory you again need a command (make directory) and an argument (the name). 

```
mkdir scripts 
```

Now we can move into that folder.
`cd` means change directory so we'll use that a lot to open different folders.
This command also has an argument.

```
cd scripts 
```

Now to get back to your home folder you can't `cd` and give it a folder name because
the computer will look in your current folder (scripts) for another folder.
Instead you need to tell the computer to "move one level up", going outside the current folder to the one containing it.

```
cd ..
```

To practice, repeat this process but make a directory called `results`.
Now list the files in your current home directory again.
Do you see the two folders you just made?

If you want to check out what is in these folders (they are currently empty but we will add to them later)
you have two options.
First, you can change directory with the `cd` command and list the contents of the folder with `ls`.
Think about these folder just like a filing cabinet.
You started off in your home folder and now you are opening the results folder.

Alternatively, list the contents of a folder by given `ls` the folder name as an argument (e.g. `ls scripts`).

We will learn lots more commands as we work through our data.


Adapted from  http://swcarpentry.github.io/shell-novice/

